[package]
name = "smart-factory-environment"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
priority-queue = "*"
uuid = { version="*", features=["v4","js"]}