name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      needs-wasm-compilation: ${{ steps.path-filter.outputs.env || steps.path-filter.outputs.wasm}}
    steps:
    - uses: actions/checkout@v3
    - uses: dorny/paths-filter@v2
      id: path-filter
      with:
        filters: |
          env:
            - 'smart-factory-environment/**'
          wasm:
            - 'smart-factory-wasm-port/**'
    - run: |
        echo "WASM=${{ steps.path-filter.outputs.wasm == 'true'}}"
        echo "ENVIRONMENT=${{ steps.path-filter.outputs.env == 'true'}}"
        echo "SHOULD_COMPILE_WASM=${{ steps.path-filter.outputs.wasm == 'true' || steps.path-filter.outputs.env == 'true'}}"
    #- name: Build
    #  run: cargo build --verbose
    #- name: Run tests
    #  run: cargo test --verbose

  build-wasm:
    needs: build
    if: needs.build.outputs.needs-wasm-compilation == 'true'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: jetli/wasm-pack-action@v0.3.0
    - name: Test WASM
      run: cd smart-factory-wasm-port && wasm-pack test --headless --chrome --firefox --node